version: '3.3'

volumes:
  pg_data:
  foodgram_static:
  foodgram_media:

services:

  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: ../backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    container_name: foodgram-back
    depends_on:
      - db
    build: ../backend
    env_file: ../backend/.env
    volumes:
      - foodgram_static:/app/static/
      - foodgram_media:/app/media/
    command: >
      sh -c "
      sleep 1 &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py loaddata ingredients_converted.json &&
      gunicorn --bind 0.0.0.0:8000 foodgram.wsgi
      "

  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /static/
    volumes:
      - foodgram_static:/static/
  
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - foodgram_static:/usr/share/nginx/html/
      - foodgram_media:/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - db
      - frontend
      - backend
